
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true

persistence:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
